# Generated by Django 3.1.3 on 2020-12-01 08:53

from django.db import migrations, models
import django.db.models.deletion
import hall.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hall', models.CharField(max_length=100, verbose_name='Название зала')),
                ('width', models.CharField(max_length=100, verbose_name='Длина по X')),
                ('length', models.CharField(max_length=100, verbose_name='Длина по Y')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
            },
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_restoran', models.CharField(max_length=100, unique=True, verbose_name='Название ресторана')),
            ],
            options={
                'verbose_name': 'restoran',
                'verbose_name_plural': 'restorans',
            },
        ),
        migrations.CreateModel(
            name='Struct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_table', models.CharField(max_length=100, verbose_name='Название стола')),
                ('position_x', hall.models.IntervalField(verbose_name='Позиция по X (%)')),
                ('position_y', hall.models.IntervalField(verbose_name='Позиция по Y (%)')),
                ('rotate', hall.models.IntervalField(default=0, verbose_name='Поворот в градусах')),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Struct',
                'verbose_name_plural': 'Structs',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_table', models.CharField(max_length=100, verbose_name='Название стола')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Длина стола по X')),
                ('length', models.PositiveSmallIntegerField(verbose_name='Длина стола по Y')),
                ('shape', models.PositiveSmallIntegerField(choices=[(0, 'ellipse'), (1, 'rectangle')], verbose_name='Форма стола')),
                ('max_seats', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('name_table', 'width', 'length'), name='inique_table'),
        ),
        migrations.AddField(
            model_name='struct',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_struct', to='hall.hall'),
        ),
        migrations.AddField(
            model_name='struct',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_struct', to='hall.table'),
        ),
        migrations.AddField(
            model_name='hall',
            name='restoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='hall.restoran'),
        ),
        migrations.AddConstraint(
            model_name='struct',
            constraint=models.UniqueConstraint(fields=('table', 'name_table', 'position_x', 'position_y'), name='unique_table_scheme'),
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('restoran', 'name_hall'), name='unique_hall'),
        ),
    ]
