# Generated by Django 3.1.3 on 2020-12-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hall',
            name='unique_hall',
        ),
        migrations.RemoveConstraint(
            model_name='table',
            name='inique_table',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='name_hall',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restoran',
            old_name='name_restoran',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='name_table',
            new_name='name',
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('restoran', 'name'), name='unique_hall'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('name', 'width', 'length'), name='inique_table'),
        ),
    ]
