# Generated by Django 3.1.3 on 2020-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_auto_20201201_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
