# Generated by Django 3.1.3 on 2020-11-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_auto_20201104_1605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('table', 'data_reserved')},
        ),
    ]
