# Generated by Django 3.1.3 on 2020-12-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_hall_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
