# Generated by Django 3.1.3 on 2020-12-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email_client',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name_client',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_client',
            new_name='phone',
        ),
    ]
