# Generated by Django 3.1.3 on 2020-12-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_auto_20201201_1611'),
        ('reserver', '0002_auto_20201201_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hall',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='hall.hall'),
            preserve_default=False,
        ),
    ]
